name: Build Minimal Ecommerce Application written in java
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/chekcout@v2

      - name: set up JDK
        uses: actions/setup-java@v2

      - name: Build with maven
        run: mvn -B package pom.xml
